modLoader="javafml"
loaderVersion="[47,)"
license="CC-BY-NC-SA-4.0"

[[mods]]
modId="uselessthings"
version="1.0.0"
displayName="没用的东西"
authors=["DeepSeek","playymcmc007"]
description="花哨的东西，似乎对生存没什么帮助"